# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: 0, yes or reverse. 0 is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

# the sequencing adapter
adapter: "/rhome/jluis/bigdata/Miniconda3/envs/bif/opt/bbmap-38.22-0/resources/adapters.fa"


ref:
  # the STAR index 
  index: "/rhome/jluis/bigdata/Tutorials/rna-seq_yeast/Pang_Sci-Reports_2016/star_index"
  # gtf file with transcripts
  annotation: "/rhome/jluis/bigdata/Tutorials/rna-seq_yeast/Mulla_elife_2017/references/Saccharomyces_cerevisiae.R64-1-1.84.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    AMB-LFplusAMB:
      - AMB
      - AMBplusLF
params:
  star: ""
  cutadapt-se: "-j 5"
  cutadapt-pe: "-j 5"
  multiqc: --fullnames --title "RNA-Seq STAR-DESeq2" 
           --comment "RNA-Seq pipeline, composed by STAR for mapping and quantification at the gene level, and DESeq2 for differential expression analysis"
